config/routes.rb
Collegeshare::Application.routes.draw do

  if Rails.env.production?
    offline = Rack::Offline.configure :cache_interval => 120 do      
      cache ActionController::Base.helpers.asset_path("application.css")
      cache ActionController::Base.helpers.asset_path("application.js")
      # cache other assets
      network "/"  
    end
    match "/application.manifest" => offline, via: [:get, :post]
  end

  root to: 'uploads#index'
  get '/search', to: 'uploads#search'
  get 'welcome', to: 'home#welcome'
  get 'profile/:id', to: 'home#profile', as: 'profile'
  get 'edit', to: 'home#edit'
  match 'edit', to: 'home#update', via: :post
  get 'following/:id', to: 'home#following', as: 'following'
  get 'followers/:id', to: 'home#followers', as: 'followers'
  get 'users', to: 'home#users'
  post 'follow', to: 'relations#create_relation' 
  post 'unfollow', to: 'relations#destroy_relation'
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks"}
	
  resources :uploads do 
    resources :comments
    collection do 
      get '/upvote/:id', to: 'uploads#upvote'
      get '/download/:id', to: 'uploads#download'
      get '/verify/:id', to: 'uploads#verify'
    end
  end

  resources :colleges do 
    resources :college_term
  end

  resources :relations, only: [:create, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#before_action :correct_user, only: [:edit, :update]

	def profile
		unless current_user
			redirect_to root_path, alert: 'You are not signed in!!'
		end
		@user = User.find params[:id]
		@uploads = @user.uploads.paginate(page: params[:page], per_page: 10) unless @user.uploads.empty?
	end

	def users
	end

	def following 
	  @user = User.find(params[:id])
	  @following = @user.following
	end

	def followers 
	  @user = User.find(params[:id])
	  @followers = @user.followers
	end

	def edit
		unless current_user
			redirect_to root_path, alert: 'You are not signed in!!'
		end
		@user = current_user
	end

	def update
		@user = User.find params[:user][:id]
		if @user.update_attributes(user_params)
			redirect_to root_path, notice: 'Profile has been succesfully updated!!'
		else
			redirect_to :back, alert: 'Profile changes were not saved due to some error!!'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :college_id)
	end

	def correct_user
	  @user = User.find(params[:id]) if params[:id]
	  redirect_to root_url , alert: 'Cannot perform this action!!' unless current_user == @user
	end
end

app/views/home/_follow.html.erb
<%= form_for(follow_path, method: 'post') do |f| %>
  <div><%= f.hidden_field :followed_id, value: @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/home/_follow_form.html.erb
<div id="follow_form">
	<% if current_user.following?(@user) %>
	  <%= render 'unfollow' %>
	<% else %>
	  <%= render 'follow' %>
	<% end %>
</div>

app/views/home/_unfollow.html.erb
<%= form_for(unfollow_path, method: 'post') do |f| %>
	<div><%= f.hidden_field :id, value: @user.id %></div>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/home/edit.html.erb
<%= form_for @user, url: edit_path, html: { method: :post } do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this from being saved:</h2>
	      <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	 	<div class="form-group">
	    <%= f.label :name %>
	    <%= f.text_field :name,value: @user.name , :autofocus => true, class: 'form-control', placeholder: 'name' %>
	  </div>

	  <div class="form-group">
	    <%= f.label :college %>
	    <%= f.select :college_id, College.all.map{ |c| [c.name, c.id]  }, { prompt: 'Select a college' }, class: 'form-control' %>
	  </div>

	  <%= f.hidden_field :id, value: current_user.id %>

    <%= f.submit "Update", class: 'default-button' %>
  
<% end %>

app/views/home/followers.html.erb
<% if @user.followers.any? %>
	<% @user.followers.each do |user| %>
		<p><%= link_to user.name, profile_path(id: user.id), method: :get  %></p>
	<% end %>
<% else %>
	<p>No followers yet..</p>
<% end %>

app/views/home/following.html.erb
<% if @user.following.any? %>
	<% @user.following.each do |user| %>
		<p><%= link_to user.name, profile_path(id: user.id), method: :get  %></p>
	<% end %>
<% else %>
	<p>Not followed anyone yet..</p>
<% end %>

app/views/home/profile.html.erb
<div class="l-page-wrapper">
    <div class="l-content-wrap">
        <div class="m-page-title">
            <h1>Profile</h1>
            <% if @user == current_user %>
            	<%= link_to edit_path(id: current_user.id) do %>
           	 		<div class="profile-edit"><i class="fa fa-edit"></i> Edit Profile</div>
            	<%end%>
			<% end %>
        </div><!-- m-page-title -->

        <div class="row">
            <div class="col-lg-12">

                <div class="row l-user-profile">
                    <div class="col-lg-3 col-md-3 col-sm-3 user-avatar">
                    	<% if @user.profile_pic.present? %>
                    		<%= image_tag @user.profile_pic %>
                    	<% else %>
	                        <a href="#"><img src="<%= asset_path('default_profile_pic.jpg') %>" /></a>
                    	<% end %>
                    </div><!-- col-lg-3 -->

                    <div class="col-lg-9 col-md-9 col-sm-9 user-info">
                        <h2><%= @user.name %></h2>
                        <% if @user.college_id %><p><%= @user.college.name %></p><% else %><p>No College Selected</p><% end %>
                        <!-- social icons -->
                    </div><!-- col-lg-9 -->
                </div>
                <div class="row l-user-profile">
                    <div class="l-user-history col-lg-12 col-md-12 col-sm-12 col-xs-12">

                        <ul>
                            <li><a href="#" class="current">Uploads</a></li>
                            <li><a href="#">Downloads</a></li>
                            <li><a href="#">Followed</a></li>
                        </ul>

                    </div>
                </div>
                <div class="row l-user-profile">
                    <div class="l-collections-posts">
                    	<% if @user.uploads.count > 0 %>
                            <%= will_paginate(@uploads) %>
                    		<% @uploads.each do |upload| %>
                    			<%= render 'uploads/card', upload: upload %>
                    		<% end %>
                    	<% else %>
                    	   <p>No uploads yet...</p>
                    	<% end %>
         

                    </div><!-- l-collections-posts row -->
                </div>




                </div><!-- row -->

            </div><!-- col-lg-12 -->
        </div><!-- row -->


    </div><!-- l-content-wrap -->
</div><!--l-page-wrapper-->

app/views/home/users.html.erb
<p><%= User.count %></p>
<% User.all.each do |user| %>
	<% if user != current_user %>
		<p><%= link_to user.name, profile_path(id: user.id), method: :get  %></p>
	<% end %>
<% end %>

app/views/home/welcome.html.erb
    <div class="col-md-6">
        <div class="l-login-wrap">
            <div class="m-login-fields">

                <div class="login-alt">
                <%= link_to user_omniauth_authorize_path(:facebook), {class: 'e-social-icon fa fa-facebook icon-facebook'} do %><% end %>
        <%= link_to user_omniauth_authorize_path(:twitter), {class: 'e-social-icon fa fa-twitter icon-twitter'} do %><% end %>
        <%= link_to user_omniauth_authorize_path(:google_oauth2), {class: 'e-social-icon fa fa-google-plus icon-googleplus'} do %>
        <% end %>

                   
                </div>

                <div class="l-separator">
                    <div class="separator-border">
                        <span class="icon-separator"></span>
                    </div><!-- separator-border -->
                </div>
                <div class="login-frame">
                  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                    <%= f.label :email, class: 'control-label col-sm-3' %>
                    <%= f.email_field :email, class: 'form-control', placeholder: 'email' %>


                    <%= f.label :password, class: 'control-label col-sm-3' %>
                    <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
                  
                    <%= f.submit "Log In", class: 'login' %>
                  <% end %>
                </div>
                <div class="register-frame hidden">
                    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                        <%= f.label :name, class: 'control-label col-sm-3' %>
                        <%= f.text_field :name, :autofocus => true, class: 'form-control', placeholder: 'name' %>

                        <%= f.label :email, class: 'control-label col-sm-3' %>
                        <%= f.email_field :email, class: 'form-control', placeholder: 'email' %>

                        <%= f.label :college, class: 'control-label col-sm-3' %>
                        <%= f.select :college_id, College.all.map{ |c| [c.name, c.id]  }, { prompt: 'Select a college' }, class: 'form-control' %>

                        <%= f.label :password, class: 'control-label col-sm-3' %>
                        <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
                        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'repeat password' %>
                      
                        <%= f.submit "Register", class: 'register' %>
                    <% end %>

                </div>
                <div class="forgot-password-frame hidden">
                    <label for="username">Username or Email</label>
                    <input type="text" class="form-control" id="username" />

                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" disabled />

                    <input type="checkbox" id="rememberme" disabled /> <label for="rememberme"> Remember Me </label>
                    <input type="button" class="forgot" value="Recover" />
                </div>



            </div><!-- .m-login-fields -->
            <a class="lostpassword" onclick="
                $(this).addClass('hidden');
                $('.signup').addClass('hidden');
                $('.back-to-login').removeClass('hidden');
                $('.login-frame').addClass('hidden');
                $('.register-frame').addClass('hidden');
                $('.forgot-password-frame').removeClass('hidden');
                ">Forgot password</a>
            <a class="signup" onclick="
                $(this).addClass('hidden');
                $('.back-to-login').removeClass('hidden');
                $('.register-frame').removeClass('hidden');
                $('.login-frame').addClass('hidden');">Create an account</a>
            <a class="back-to-login hidden" onclick="
                $(this).addClass('hidden');
                $('.signup').removeClass('hidden');
                $('.lostpassword').removeClass('hidden');
                $('.login-frame').removeClass('hidden');
                $('.register-frame').addClass('hidden');
                $('.forgot-password-frame').addClass('hidden');">Use existing account</a>
        </div>
    </div>
    <div class="col-md-6">
        <div class="index-wrap">
            <div class="container">
                <div class="logo">
                    <img src="<%= asset_path('logo_black.svg') %>" alt="Logo" class="logo-img"/>
                    <h1 class="logo-text">CollegeShare</h1>
                </div>
            </div>
            <img src="<%= asset_path('home.jpg') %>" alt="Loading image..."/>
            <div class="container">
                <h2 align="center">Upload | Share | Download</h2>
                <h6 align="center">A place where students share resources to help each other survive college.</h6>
            </div>
        </div>
    </div>