config/routes.rb
Collegeshare::Application.routes.draw do

  if Rails.env.production?
    offline = Rack::Offline.configure :cache_interval => 120 do      
      cache ActionController::Base.helpers.asset_path("application.css")
      cache ActionController::Base.helpers.asset_path("application.js")
      # cache other assets
      network "/"  
    end
    match "/application.manifest" => offline, via: [:get, :post]
  end

  root to: 'uploads#index'
  get '/search', to: 'uploads#search'
  get 'welcome', to: 'home#welcome'
  get 'profile/:id', to: 'home#profile', as: 'profile'
  get 'edit', to: 'home#edit'
  match 'edit', to: 'home#update', via: :post
  get 'following/:id', to: 'home#following', as: 'following'
  get 'followers/:id', to: 'home#followers', as: 'followers'
  get 'users', to: 'home#users'
  post 'follow', to: 'relations#create_relation' 
  post 'unfollow', to: 'relations#destroy_relation'
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks"}
	
  resources :uploads do 
    resources :comments
    collection do 
      get '/upvote/:id', to: 'uploads#upvote'
      get '/download/:id', to: 'uploads#download'
      get '/verify/:id', to: 'uploads#verify'
    end
  end

  resources :colleges do 
    resources :college_term
  end

  resources :relations, only: [:create, :destroy]
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	validates_presence_of :name, :description, :user_id
	mount_uploader :link, UploadUploader
	default_scope { order(no_of_downloads: :desc, upvotes: :desc) }
	has_many :comments, as: :owner, dependent: :destroy
	has_many :upload_upvotes, dependent: :destroy
	# has_many :taggings, dependent: :destroy
	has_many :downloads, dependent: :destroy
  	# has_many :tags, through: :taggings
  	belongs_to :user
  	#after_save :create_taggings
	#after_save :enqueue_upload

	def filename
		File.basename(link.path || link.filename) if link
	end

	def self.search(query)
		Upload.where('lower(name) LIKE :query OR lower(description) LIKE :query', query: "%#{query.downcase}%")
	end

	def save_upload_params
		@upload.key = params[:key]
    	@upload.remote_link_url = @upload.link.direct_fog_url(with_path: true)
    	@upload.upload_processed = true
    	@upload.save!
	end

	def enqueue_upload
		UploadWorker.perform_async(id, key) if key.present?
	end

	class UploadWorker
		include Sidekiq::Worker

		def perform(id, key)
			upload = Upload.find(id)
			upload.key = key
			upload.remote_link_url = upload.link.direct_fog_url(with_path: true)
			upload.upload_processed = true
			upload.save!
		end
	end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy, :download, :upvote, :verify]
  before_action :authenticate_user!, except: [:index, :search]
  before_action :is_owner, only: [:edit, :update, :destroy]
  before_action :college_set, only: [:create, :destroy, :edit]

  def index
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
    @uploads = Upload.all
    @uploader = Upload.new.link
    @uploads = @uploads.paginate(page: params[:page], per_page: 10) unless @uploads.empty?
    if Rails.env == 'development'
      @uploader.success_action_redirect = "http://localhost:3003/uploads/new"
    elsif Rails.env == 'production' 
      @uploader.success_action_redirect = "http://www.collegeshare.in/uploads/new"
    end
  end

  def search
    @uploads = Upload.search(params[:query])
    @uploads = @uploads.paginate(page: params[:page], per_page: 10) unless @uploads.empty? or @uploads.empty?
  end

  def download
    @download = @upload.downloads.create! user_id: current_user.id
    if @download and @upload.update_attributes!(no_of_downloads: @upload.downloads.count)
      render status: 200, json: @upload
    else
      render status: 422, json: {message: "Upload could not be downloaded!!"}
    end
  end

  def upvote
    @upvote = @upload.upload_upvotes.create! user_id: current_user.id
    if @upvote and @upload.update_attributes!(upvotes: @upload.upload_upvotes.count)
      render status: 200, json: @upload
    else
      render status: 422, json: {message: "Upload could not be upvoted!"}
    end
  end

  def verify
    if @upload and @upload.update_attributes!(verified: !@upload.verified)
      render status: 200, json: @upload
    else
      render status: 422, json: {message: "Upload's verification could not be upadted!"}
    end
  end

  def show
  end

  def new
    @upload = Upload.new(key: params[:key])
  end


  def edit

  end

  def create
    @upload = Upload.new(upload_params)
    @upload.user_id = current_user.id
      if @upload.save
        redirect_to upload_path(id: @upload.id), notice: 'File has been successfully uploaded!'
      else
        redirect_to :back, alert: 'Upload was not saved!!'
      end
  end

  def update
    respond_to do |format|
      if @upload.update(upload_update_params)
        format.html { redirect_to upload_path(id: @upload.id), notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    def set_upload
      @upload = Upload.find(params[:id])
    end

    def upload_params
      params.require(:upload).permit(:name, :description, :key)
    end

    def upload_update_params
      params.require(:upload).permit(:name, :description, :upvotes, :no_of_downloads, :key)
    end
end

app/views/uploads/_card.html.erb
<div class="collections-post news-feed" id=<%= upload.id %>>
    <div class="col-md-4">
        <div class="container">
            <div class="row main-details">
                <div class="l-post-image">
                    <%= image_tag "file-icons/#{upload.filename.split('.').last.downcase}.png" %>
                </div><!-- l-post-image  -->
                <div class="collections-icons collections-icons-main">
                    <div data-toggle="tooltip" data-placement="top" title="size"><i class="fa fa-fw fa-file"></i>
                        <% if upload.link.file.size / (1024**2) != 0 %>
                            <%= upload.link.file.size / (1024**2) %> MB
                        <% else %>
                            <%= upload.link.file.size / 1024 %> KB
                        <% end %>
                    </div>
                    <div data-toggle="tooltip" data-placement="top" title="downloads"><i class="fa fa-fw fa-download"></i><span class="no-of-downloads"><%= upload.no_of_downloads %></span></div>
                    <div class="row"> 
                        <div class="upvote-button" data-toggle="tooltip" data-placement="top" title="upvotes"><i class="fa fa-fw fa-thumbs-up" data-toggle="tooltip" data-placement="top" title="upvote"></i><span class="no-of-upvotes"><%= upload.upvotes %></span></div>
                        <div data-toggle="tooltip" data-placement="top" title="comments"><i class="fa fa-fw fa-comments"></i><%= upload.comments.count %></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="collections-icons">
                    <% if current_user.present? %>
                        <div class="btn btn-primary download-button" onclick="location.href='<%= upload.link_url %>'">
                          <i class="fa fa-2x fa-fw fa-download"></i>
                        </div>
                        <div class="g-savetodrive-parent" onmouseover="$(this).children('.g-savetodrive-wrapper').stop(true,false).fadeIn();" onmouseout="$(this).children('.g-savetodrive-wrapper').stop(true,false).delay(1500).fadeOut();">
                          <div class="g-savetodrive-wrapper">
                            <div class="g-savetodrive" data-src="<%= upload.link_url %>" data-filename="<%= upload.filename %>" data-sitename="CollegeShare"></div>
                          </div>
                          <div class="btn btn-primary g-savetodrive-button">
                              <i class="fa fa-2x fa-fw fa-cloud-download"></i>
                          </div>
                        </div>
                    <% else %>
                       <%= link_to(root_path) do %>
                         <p>Login to download.</p>
                       <% end %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="collections-icons">
            <% if upload.verified %>
                <div class="row">
                    <div><i class="fa fa-fw fa-check-circle"></i>Verfied</div>
                </div>
            <% end %>
            <div class="row">
                <div data-toggle="tooltip" data-placement="top" title="shared by"><i class="fa fa-fw fa-user"></i> <%= link_to profile_path(id: upload.user.id) do %><%= upload.user.name %><% end %>
                </div>
            </div>
            <div class="row">
                <div data-toggle="tooltip" data-placement="top" title="shared on"><i class="fa fa-fw fa-upload"></i><%= upload.created_at.localtime.strftime("%B %d, %Y") %></div>
            </div>
        </div>
    </div>
  <div class="col-md-8">
    <%= link_to upload_path(upload) do %>
        <h3><%= upload.name %></h3>
    <% end %>
    <p><%= upload.user.college.name %></p>
    <p><%= upload.description %></p>
  </div>
</div>

<div class="l-separator">
    <div class="separator-border">
        <span class="icon-separator"></span>
    </div><!-- separator-border -->
</div>

app/views/uploads/_form.html.erb
<div class="col-md-6">
    <div class="l-login-wrap upload">
        <div class="m-login-fields upload">
            <div class="login-frame">
                <%= form_for(@upload) do |f| %>
                  <% if @upload.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

                      <ul>
                      <% @upload.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>

                    <div class="form-group"> 
                      <%= f.label :name %>
                      <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'name' %>
                    </div>
                    <div class="form-group"> 
                      <%= f.label :description %>
                      <%= f.text_field :description, autofocus: true, class: 'form-control', placeholder: 'description' %>
                      <p>Do no forget to add tags eg: #OperatingSystems   #cs   #notes #qp</p>
                    </div>

                    <%= f.hidden_field :key %>

                    <p>Upload file name : <%= @upload.filename %></p>

                    <%= f.submit "Post", class: 'default-button' %>
                <% end %>
            </div>
        </div><!-- .m-login-fields -->
    </div>
</div>

app/views/uploads/create.js.erb
<% if @upload.new_record? %>
  alert("Failed to upload painting: <%= j @upload.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#uploads").append("<%= j render(@upload) %>");
<% end %>

app/views/uploads/edit.html.erb
<%= render 'form' %>

app/views/uploads/index.html.erb
<div class="right-pane">
    <div class="container">
        <div class="l-content-wrap">
            <div class="m-page-title">
                <h1>Upload</h1>
            </div><!-- m-page-title -->
            <div class="container">
                <div class="col-md-6">
                    <div class="index-wrap upload">
                        <img src="<%= asset_path('logo_black.svg') %>" width="200px" alt="Loading image..."/>
                        <div class="l-login-wrap upload">
                            <div class="m-login-fields upload">
                                <div class="login-frame">
                                    <%= direct_upload_form_for @uploader do |f| %>
                                       <div class="form-group">
                                         <label for="file">File Path</label>
                                         <%= f.file_field :link, id: 'file_upload', class: 'form-control', type: 'file' %>
                                       </div>
                                       <div>
                                           <%= f.submit "Upload", class: 'login' %>
                                       </div>
                                    <% end %>      
                                </div>
                            </div><!-- .m-login-fields -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <div class="l-content-wrap">
                    <div class="m-page-title">
                        <h1>Share Feed</h1>
                    </div><!-- m-page-title -->
                    <div class="l-collections-posts">

                    <% if @uploads.count > 0 %>
                       <%= will_paginate @uploads %>
                         <% @uploads.each do |upload| %>
                           <%= render 'uploads/card', upload: upload %>
                         <% end %>
                     <% else %>
                       No uploads yet..
                     <% end %>

                    </div><!-- l-collections-posts row -->
                </div>
            </div>
        </div>
    </div>
</div>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/search.html.erb
<div class="row">
    <div class="container">
        <div class="l-content-wrap">
            <div class="m-page-title">
                <h1>Search Results</h1>
            </div><!-- m-page-title -->
            <div class="l-collections-posts">

            <% if @uploads.count > 0 %>
               <%= will_paginate @uploads %>
                 <% @uploads.each do |upload| %>
                   <%= render 'uploads/card', upload: upload %>
                 <% end %>
             <% else %>
               No results found..
             <% end %>

            </div><!-- l-collections-posts row -->
        </div>
    </div>
</div>

app/views/uploads/show.html.erb
	<div class="container">
	    <div class="collections-post news-feed show" id="<%= @upload.id %>">
	        <div class="col-md-4">
	            <div class="container">
	                <div class="row main-details">
	                    <div class="l-post-image">
	                    	<%= image_tag "file-icons/#{@upload.filename.split('.').last.downcase}.png" %>
	                    </div><!-- l-post-image  -->
	                    <div class="collections-icons collections-icons-main">
	                        <div data-toggle="tooltip" data-placement="top" title="size"><i class="fa fa-fw fa-file"></i>
	                        	<% if @upload.link.file.size / (1024**2) != 0 %>
	                        		<%= @upload.link.file.size / (1024**2) %> MB
	                        	<% else %>
	                        		<%= @upload.link.file.size / 1024 %> KB
	                        	<% end %>
	                        </div>
	                        <div data-toggle="tooltip" data-placement="top" title="downloads"><i class="fa fa-fw fa-download"></i><span class="no-of-downloads"><%= @upload.no_of_downloads %></span></div>
	                        <div class="row">
	                            <div class="upvote-button" data-toggle="tooltip" data-placement="top" title="upvotes"><i class="fa fa-fw fa-thumbs-up" data-toggle="tooltip" data-placement="top" title="upvote"></i><span class="no-of-upvotes"><%= @upload.upvotes %></span></div>
	                            <div data-toggle="tooltip" data-placement="top" title="comments"><i class="fa fa-fw fa-comments"></i><%= @upload.comments.count %></div>
	                        </div>
	                    </div>
	                </div>
	                <div class="row">
	                    <div class="collections-icons">
	                        <div class="btn btn-primary download-button" onclick="location.href='<%= @upload.link_url %>'">
		                      <i class="fa fa-2x fa-fw fa-download"></i>
			                </div>
			                <div class="g-savetodrive-parent" onmouseover="$(this).children('.g-savetodrive-wrapper').stop(true,false).fadeIn();" onmouseout="$(this).children('.g-savetodrive-wrapper').stop(true,false).delay(1500).fadeOut();">
                      		  <div class="g-savetodrive-wrapper">
                                <div class="g-savetodrive" data-src="<%= @upload.link_url %>" data-filename="<%= @upload.filename %>" data-sitename="CollegeShare"></div>
                              </div>
			                  <div class="btn btn-primary g-savetodrive-button">
			                      <i class="fa fa-2x fa-fw fa-cloud-download"></i>
			                  </div>
			                </div>
		                </div>
		            </div>
		            <div class="collections-icons">
			            <% if @upload.verified %>
		                <div class="row">
		                    <div><i class="fa fa-fw fa-check-circle"></i>Verfied</div>
		                </div>
		            	<% end %>
		                <div class="row">
		                    <div data-toggle="tooltip" data-placement="top" title="shared by"><i class="fa fa-fw fa-user"></i><%= link_to profile_path(id: @upload.user) do %><%= @upload.user.name %>
		                    <% end %></div>
		                </div>
		                <div class="row">
		                    <div data-toggle="tooltip" data-placement="top" title="shared on"><i class="fa fa-fw fa-upload"></i><%= @upload.created_at.localtime.strftime('%B %d, %Y') %></div>
		                </div>
		            </div>
	        	</div>
	        </div>
	        <div class="col-md-8">
	            <h3><%= @upload.name %></h3>
	            <p><%= @upload.user.college.name %></p>
	            <p><%= @upload.description %></p>

			    <% if current_user.owner? @upload or current_user.admin? %>
			    	<%= link_to 'Edit', edit_upload_path(@upload) %> |
			    	<%= link_to 'Destroy', @upload, method: :delete, data: { confirm: 'Are you sure?' } %>
			    <% end %>
	        </div>
	    </div>

	    <div class="l-separator">
	        <div class="separator-border">
	            <span class="icon-separator"></span>
	        </div><!-- separator-border -->
	    </div>

	    <div class="col-md-8 col-md-offset-2 comments-section">
	        <h2><%= pluralize(@upload.comments.count, 'Comment') %></h2>
	        <!-- comment -->
	        	<%= render 'comments/upload_comments'%>
	        <!-- comment -->
	        <div class="row">
	        
		        <div class="l-separator">
		            <div class="separator-border">
		                <span class="icon-separator"></span>
		            </div><!-- separator-border -->
		        </div>

		        <%= render 'comments/upload_comment_form' %>
            </div>
        </div>
	</div>