config/routes.rb
Collegeshare::Application.routes.draw do

  if Rails.env.production?
    offline = Rack::Offline.configure :cache_interval => 120 do      
      cache ActionController::Base.helpers.asset_path("application.css")
      cache ActionController::Base.helpers.asset_path("application.js")
      # cache other assets
      network "/"  
    end
    match "/application.manifest" => offline, via: [:get, :post]
  end

  root to: 'uploads#index'
  get '/search', to: 'uploads#search'
  get 'welcome', to: 'home#welcome'
  get 'profile/:id', to: 'home#profile', as: 'profile'
  get 'edit', to: 'home#edit'
  match 'edit', to: 'home#update', via: :post
  get 'following/:id', to: 'home#following', as: 'following'
  get 'followers/:id', to: 'home#followers', as: 'followers'
  get 'users', to: 'home#users'
  post 'follow', to: 'relations#create_relation' 
  post 'unfollow', to: 'relations#destroy_relation'
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks"}
	
  resources :uploads do 
    resources :comments
    collection do 
      get '/upvote/:id', to: 'uploads#upvote'
      get '/download/:id', to: 'uploads#download'
      get '/verify/:id', to: 'uploads#verify'
    end
  end

  resources :colleges do 
    resources :college_term
  end

  resources :relations, only: [:create, :destroy]
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |name, msg| %>
	<% if name == :alert %>
		<div class="alert alert-danger alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert">
				<span aria-hidden="true" class="fui-cross"></span>
				<span class="sr-only">Close</span>
			</button>
			<%= msg %>
		</div>
	<% else %>
		<div class="alert alert-success alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert">
				<span aria-hidden="true" class="fui-cross"></span>
				<span class="sr-only">Close</span>
			</button>
			<%= msg %>
		</div>
	<% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to root_path do %>
                <div class="logo navbar-brand">
                    <img src="<%= asset_path('logo.svg') %>" alt="Logo" class="logo-img"/>
                    <h3 class="logo-text">CollegeShare</h3>
                </div>
            <% end %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                    <li>
                        <%= link_to "Profile", profile_path(id: current_user.id), method: :get %>
                    </li>
                    <li>
                       <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<%= form_tag(search_path, method: 'get', role: 'search') do  %>
        <div class="form-group">
            <%= text_field_tag :query, params[:query], class: 'form-control form-search', placeholder: 'Search Our Galaxy of Shares ...', id: 'search' %>
        </div>
<% end %>

app/views/layouts/_stats.html.erb
<div class="row">
  <div class="stats col-md-3">
    <a href="<%= following_path(id: @user.id) %>">
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
      following
    </a>
    |
    <a href="<%= followers_path(id: @user.id) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      followers
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
  <title><% image_tag "logo.png", size: '240x50' %>Collegeshare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
  <script src="https://apis.google.com/js/platform.js"></script>
</head>
<body class="index">
	<%= render 'layouts/header' %>
   <div class="container">
		 <%= render 'layouts/flash_message' %>
			  <%= yield %>
   </div>
</body>
</html>